### ISSUE TITLE
Brak instrukcji do uruchomienia

### ISSUE THREAD

**Issue by interduo** [jarek-mazur-allegro/flashcards#1]
Dzień dobry,
Chciałem odpalić tą znaną aplikację, jednakże nie wiem jak - brak instrukcji

Pozdrawiam serdecznie

**Comment by interduo** [comment]
@jarek-mazur-allegro is project abandoned?

**Comment by jarek-mazur-allegro** [comment]
> @jarek-mazur-allegro is project abandoned?

It was training project, do you want to use it? ;)

**Comment by interduo** [comment]
Pracuj w robocie a nie się szwagier opierdzielasz :D
